name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui/invoice-generator-ui:latest .

      - name: Push Docker image to Container Registry
        run: |
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui/invoice-generator-ui:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy invoice-generator-ui \
            --image europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui/invoice-generator-ui:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated