name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui invoice-generator-backend:latest .
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui/invoice-generator-ui:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy react-app \
            --image europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/invoice-generator-ui/invoice-generator-ui:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
